# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Aditi Kabra
email: ank55@cornell.edu
description: PhD student in Computer Science at Carnegie Mellon University
short_description: 
long_description:
  I'm a third year PhD student at Carnegie Mellon University, advised by André Platzer at the <a href="https://www.ls.cs.cmu.edu/">Logical Systems Lab</a>.
  I am interested in the synthesis of controllers for cyber physical systems, and more generally in formal methods.
  I'm excited about scaling verified controller design to handle greater complexity and require lower manual effort.
  I have worked on <a href="assets/train-control-emsoft-preprint.pdf">formally verified train control</a>.<br>
  Previously, I was software engineer at Microsoft, and worked in the Azure reserved instances team.
  As an undergraduate at Cornell, I was a part of <a href="https://capra.cs.cornell.edu/">Capra</a>, where I contributed to Gator, a domain specific programming language for geometry types, and worked on an algorithm to efficiently verify the commutativity of diagrams such as those representing the transformation between types.
  I also worked on understanding the scope and applications of Gaussian Boson Sampling at the <a href="https://mcmahon.aep.cornell.edu/">McMahon Lab</a>.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: allikabra
github_username:  aditink

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
