# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Aditi Kabra
email: ank55@cornell.edu
description: >- # Actually don't want to show anything in that footer space right now.
short_description: >- 
        I'm a software engineer at Microsoft with research interests in programming languages and theory.
        As an undergraduate at Cornell, I worked on a domain specific programming language for geometry types, and on the applications and limitations of a Gaussian Boson Sampling device.
        I am currently working on efficiently verifying path information properties over the course of online addition to a graph.

long_description: >- # this means to ignore newlines until "baseurl:"
  I'm currently a software engineer at Microsoft, and work in the Azure reserved instances team.
  My research interests lie broadly in programming languages and theory.
  As an undergraduate at Cornell, I was a part of Capra, where I contributed to Gator, a domain specific programming language for geometry types.
  I also worked on understanding the scope and applications of Gaussian Boson Sampling at the McMahon Lab.
  I am currently working on how to efficiently verify path independence of morphisms over the course of online addition to a category,
  a problem that finds application in situations like the compilation of programs with implicit type conversion.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: allikabra
github_username:  aditink

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
